image: python:3.8

stages:
 - test

before_script:
  - "pip install -U platformio"

job:
  stage: test
  script: "platformio run -e esp12e"
  artifacts:
    paths:
      - .pio/build/esp12e/firmware.elf
    expire_in: 1 week
